config:
  argocd:
    grpcWeb: true
    serverAddress: "https://argocd-server.argocd-qa.svc.cluster.local"
    insecure: true
    plaintext: false
  registries:
    - name: Harbor Private Registry
      api_url: https://registry.cgraaaj.in
      prefix: registry.cgraaaj.in
      ping: true
      credentials: pullsecret:argocd-qa/regcred

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
