apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-qa
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.2/manifests/ha/install.yaml

patches:
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: argocd-qa
    target:
      kind: ClusterRoleBinding
