apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mediaradar-svc
  namespace: argocd-qa
spec:
  project: apps
  source:
    repoURL: https://github.com/cgraaaj/media-radar-svc.git
    path: k8s
    targetRevision: master
    helm:
      valueFiles:
        - values-qa.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mediaradar-svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: 
      prune: true
      selfHeal: true
    # Enable Istio sidecar injection for this namespace
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled