apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stockx-svc
  namespace: argocd-qa
spec:
  project: apps
  source:
    repoURL: https://github.com/cgraaaj/stockx-svc-k8s.git
    path: .
    targetRevision: main
    helm:
      valueFiles:
        - values-qa.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: stockx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: 
      prune: true
      selfHeal: true
