loki:
  auth_enabled: false
  isDefault: false
  url: http://loki.loki.svc.cluster.local:3100
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics

  persistence:
    enabled: true
    existingClaim: loki-pvc
  
  config:
    limits_config:
      volume_enabled: true
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h # 7 days

    schema_config:
      configs:
        - from: 2024-12-01
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: index_loki_
            period: 24h
    storage_config:
      aws:
        s3: "http://minio.minio.svc.cluster.local:9000"
        bucketnames: "loki-bucket"
        access_key_id: "rootuser"
        secret_access_key: "rootpass1345"
        s3forcepathstyle: true
      boltdb_shipper:
          active_index_directory: /data/loki/boltdb-shipper-active
          shared_store: s3
    