apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sa-cache-manager
  namespace: argocd-qa
spec:
  project: cronjobs
  source:
    repoURL: https://github.com/cgraaaj/k8s-cronjob.git
    targetRevision: master
    path: sa-cache-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cronjobs
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
