---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cgraaaj-in-staging
  namespace: nginx-test
spec:
  secretName: nginx-cgraaaj-in-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "nginx.cgraaaj.in"
  dnsNames:
  - "nginx.cgraaaj.in"