apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  annotations:
    reloader.stakater.com/match: "true"
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  server.insecure: "true"
  # redis.server: argocd-redis-ha-haproxy:6379