---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cgraaaj-in
  namespace: argocd
spec:
  secretName: argocd-cgraaaj-in-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "argocd.cgraaaj.in"
  dnsNames:
  - "argocd.cgraaaj.in"
