---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: coder-cgraaaj-in
  namespace: coder
spec:
  secretName: coder-cgraaaj-in-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "coder.cgraaaj.in"
  dnsNames:
  - "coder.cgraaaj.in"
