apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stockx-svc-dev-cgraaaj-in
  namespace: stockx
spec:
  secretName: stockx-svc-dev-cgraaaj-in-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "stockx-svc.dev.cgraaaj.in"
  dnsNames:
    - "stockx-svc.dev.cgraaaj.in"
