---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cgraaaj-in
  namespace: test
spec:
  secretName: test-cgraaaj-in-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "test.cgraaaj.in"
  dnsNames:
  - "test.cgraaaj.in"
