---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-cgraaaj-in
  namespace: traefik
spec:
  secretName: traefik-cgraaaj-in-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "traefik.cgraaaj.in"
  dnsNames:
  - "traefik.cgraaaj.in"
