apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-runner
  namespace: argocd-qa
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
    - repoURL: https://charts.gitlab.io
      chart: gitlab-runner
      targetRevision: 0.68.1
      helm:
        valueFiles:
          - $values/gitlab-runner/values.yaml
    - repoURL: https://github.com/cgraaaj/k3s-infra.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab-runner
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
