apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-servicemonitors
  namespace: argocd-qa
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/cgraaaj/k3s-infra.git
    targetRevision: master
    path: monitoring/istio-servicemonitors
    directory:
      recurse: false
      include: 'servicemonitor-*.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: monitoring.coreos.com
      kind: ServiceMonitor
      jqPathExpressions:
        - .spec.endpoints[]?.relabelings[]?.action
