apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-replicator
  namespace: argocd-qa
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://helm.mittwald.de
    chart: kubernetes-replicator
    targetRevision: 2.12.3
  destination:
    server: https://kubernetes.default.svc
    namespace: kubernetes-replicator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
