apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd-qa
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki-stack
      targetRevision: 2.10.3
      helm:
        releaseName: loki
        valueFiles:
          - $values/monitoring/loki-stack/values.yaml
    - repoURL: https://github.com/cgraaaj/k3s-infra.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
