apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd-qa
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.11.1
      helm:
        valueFiles:
          - $values/longhorn/values.yaml
    - repoURL: https://github.com/cgraaaj/k3s-infra.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
