apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ignite
  namespace: ignite
spec:
  serviceName: ignite
  replicas: 3  # Multiple Ignite nodes
  selector:
    matchLabels:
      app: ignite
  template:
    metadata:
      labels:
        app: ignite
    spec:
      containers:
      - name: ignite
        image: apacheignite/ignite:2.15.0
        ports:
          - containerPort: 10800  # Client API
          - containerPort: 47500  # Cluster communication
          - containerPort: 47100  # Discovery
        volumeMounts:
          - name: config-volume
            mountPath: /ignite/config
          - name: ignite-storage
            mountPath: /ignite/data
        env:
          - name: CONFIG_URI
            value: "file:///ignite/config/default-config.xml"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
      volumes:
      - name: config-volume
        configMap:
          name: ignite-config
  volumeClaimTemplates:
  - metadata:
      name: ignite-storage
      namespace: ignite
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: longhorn-retain  # Replace with your storage class
