apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ignite-pvc
  namespace: ignite
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: longhorn-retain # Use your storage class (e.g., local-path, longhorn)
