apiVersion: v1
kind: Service
metadata:
  name: ignite
  namespace: ignite
spec:
  selector:
    app: ignite
  ports:
    - name: client
      protocol: TCP
      port: 10800
      targetPort: 10800
    - name: cluster
      protocol: TCP
      port: 47500
      targetPort: 47500
    - name: discovery
      protocol: TCP
      port: 47100
      targetPort: 47100
  clusterIP: None  # Headless service for StatefulSet
